# Generated by Django 2.0.2 on 2018-03-03 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djradicale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nom, Prénom du Client')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('state', models.BooleanField(default=False, verbose_name='Etat')),
                ('event_date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('description', models.TextField(verbose_name='description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email Client')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 3, 1, 20, 13, 56, 213157), verbose_name='publication date')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow comments')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djradicale.DBCollection')),
            ],
            options={
                'verbose_name': 'Rendez-Vous',
                'get_latest_by': 'event_date',
                'ordering': ['-event_date', '-start_time', '-title'],
                'permissions': (('change_author', 'Change author'),),
                'verbose_name_plural': 'Rendez-Vous',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type de Services')),
                ('duration', models.TimeField(default=None, verbose_name='Durée')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'verbose_name': 'Service',
            },
        ),
    ]
