# Generated by Django 2.2.12 on 2024-01-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
