# Generated by Django 2.0.3 on 2018-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='online_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
