# Generated by Django 2.2.12 on 2020-05-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_auto_20200518_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
    ]
