# Generated by Django 2.2.12 on 2020-05-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0008_auto_20200518_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='Nom'),
        ),
    ]
