# Generated by Django 2.2.12 on 2020-05-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_slider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
