version: '3.8'

services:

  calendar:
    build: ./easyappointments
    volumes:
      - ./easyappointments/assets/99-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./easyappointments/assets/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - calendar_data:/var/www/html
    ports:
      - "8003:80"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointment

  frontend:
    build: ./website
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - cms

  cms:
    build: ./cms
    volumes:
      - kirby_data:/var/www/html
    ports:
      - "8002:80"
    restart: always
    env_file:
      - ./cms/id.env

volumes:
  kirby_data:
  calendar_data:
