tabs:
  content:
    label:
      en: Content
      fr: Contenu
    icon: text
    columns:
      sidebar:
        width: 1/4
        sticky: true
        sections:
          title:
            type: fields
            fields:
              title:
                label:
                  en: Title
                  fr: Titre
                type: text
                required: true
          cover:
            type: fields
            fields:
              sep:
                type: line
              cover:
                label:
                  en: Cover image
                  fr: Image de couverture
                type: files
                max: 1
                layout: cards
                required: true
                uploads:
                  template: image
      main:
        width: 3/4
        type: fields
        fields:
          introTitle:
            label:
              en: Intro title
              fr: Titre introduction
            type: text
            required: true
          intro:
            label:
              en: Intro
              fr: Introduction
            type: textarea
            required: true

  seo: tabs/seo
