title:
  en: Project
  fr: Projet

extends: pages/event-project-base

status:
  draft: true
  listed: true

num: zero

options:
  preview: "{{ page.frontendUrl }}"

tabs:
  content:
    columns:
      sidebar:
        sections:
          taxonomies:
            type: fields
            fields:
              sepTaxonomies:
                type: line
              year:
                label:
                  en: Year
                  fr: Année
                help:
                  en: Only used to filter projects on the projects page.
                  fr: Utilisée uniquement pour filtrer les projets sur la page des projets.
                type: number
                step: 1
                min: 1900
                max: 2200
              projectThemes:
                extends: fields/taxonomies/project-themes
              projectTypes:
                extends: fields/taxonomies/project-types
      main:
        sections:
          collective:
            type: fields
            fields:
              collectiveLabel:
                label:
                  en: Collective
                  fr: Collectif
                type: headline
              collectiveName:
                label:
                  en: Collective name
                  fr: Nom du collectif
                type: text
              collectiveMembers:
                label:
                  en: Collective members
                  fr: Membres du collectif
                type: structure
                fields:
                  name:
                    label:
                      en: Name
                      fr: Nom
                    type: text
                    required: true
