# Generated by Django 3.2.23 on 2024-01-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djradicale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo de la coupe - 600 x 600')),
            ],
            options={
                'verbose_name': 'Coupe',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nom du salon')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Numero de Telephone')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Email')),
                ('color', models.CharField(default='', max_length=10, verbose_name='Couleur')),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo du salon - 600 x 1000')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
            ],
            options={
                'verbose_name': 'Barbershop',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10, verbose_name='Jours')),
                ('day_id', models.IntegerField(default=0, verbose_name='Identifiant du Jour - Lundi 0, Dimanche 6')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closed_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.location')),
            ],
            options={
                'verbose_name': "Heure d'ouverture",
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo - 650x720')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Première Page')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
                ('online_appointment', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djradicale.dbcollection')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.location')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbier',
            },
        ),
    ]
