# Generated by Django 3.2.23 on 2024-01-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cut',
        ),
    ]
