tabs:

  content:

    label:
      en: Content
      fr: Contenu

    icon: text

    columns:

      - width: 1/2

        sections:

          pages:
            type: pages
            creates: forpro
            templates:
              - forpro
              - default
              - home

  seo: tabs/seo-site
