tabs:
  content:
    label:
      en: Content
      fr: Contenu

    icon: text

    columns:
      - width: 1/2

        fields:
          files:
            label:
              en: Files
              fr: Fichiers
            type: files
            layout: cards

      - width: 1/2

        sections:
          global:
            create: false
            label: "Global"
            type: pages
            templates:
              - site-info
              - home

          pages:
            type: pages
            templates:
              - forpro

  booking: tabs/booking

  seo: seo/site
