tabs:

  content:

    label:
      en: Content
      fr: Contenu

    icon: text

    columns:

      - width: 1/2

        fields:
          files:
            label:
              en: Files
              fr: Fichiers
            type: files
            layout: cards

      - width: 1/2

        sections:

          pages:
            type: pages
            creates: forpro
            templates:
              - forpro
              - default
              - site-info

  seo: tabs/seo-site
