FROM node:24-alpine AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

USER node:node

WORKDIR /app

COPY --from=builder --chown=node:node /app/build ./build
COPY --from=builder --chown=node:node /app/node_modules ./node_modules

COPY --chown=node:node package.json pnpm-lock.yaml* ./

CMD ["node", "build"]