# Generated by Django 2.0.2 on 2018-03-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djradicale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo - 650x720')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Première Page')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
            ],
            options={
                'verbose_name': 'Barbier',
            },
        ),
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nom du salon')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Numero de Telephone')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Email')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Adresse')),
                ('color', models.CharField(default='', max_length=10, verbose_name='Couleur')),
                ('form_url', models.CharField(default='', max_length=255)),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo du salon - 600 x 1000')),
                ('picture_appointment', models.ImageField(default='', upload_to='', verbose_name='Photo rendez-vous - 1000 x 686')),
                ('banner', models.ImageField(default='', upload_to='', verbose_name='Bannière - 1920 x 1080')),
                ('meta_title', models.CharField(default='', max_length=60, verbose_name='Titre')),
                ('meta_description', models.TextField(default='', max_length=140, verbose_name='Description')),
                ('meta_tag', models.CharField(default='', max_length=140, verbose_name='Tag')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
            ],
            options={
                'verbose_name': 'Barbershop',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Pays')),
                ('code', models.CharField(default='', max_length=5, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('picture', models.ImageField(default='', upload_to='', verbose_name='Photo de la coupe - 600 x 600')),
            ],
            options={
                'verbose_name': 'Coupe',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=25, verbose_name='Ville')),
                ('code', models.CharField(default='', max_length=10, verbose_name='NPA')),
                ('address', django_google_maps.fields.AddressField(default='', max_length=200, verbose_name='Adresse')),
                ('geolocation', django_google_maps.fields.GeoLocationField(default='', max_length=100, verbose_name='Coordonées')),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Country')),
            ],
            options={
                'verbose_name': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom de la formule')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description de la formule')),
                ('detail', models.CharField(default='', max_length=250, verbose_name='Détail de la formule')),
                ('price', models.CharField(default='', max_length=10, verbose_name='Prix')),
                ('column_id', models.IntegerField(default=0, verbose_name='Numéro de la colonne - Affichage')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Barbershop')),
            ],
            options={
                'verbose_name': 'Formule',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10, verbose_name='Jours')),
                ('day_id', models.IntegerField(default=0, verbose_name='Identifiant du Jour - Lundi 0, Dimanche 6')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closed_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Barbershop')),
            ],
            options={
                'verbose_name': "Heure d'ouverture",
            },
        ),
        migrations.AddField(
            model_name='barbershop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Location'),
        ),
        migrations.AddField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Barbershop'),
        ),
        migrations.AddField(
            model_name='barber',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djradicale.DBCollection'),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
