# Generated by Django 2.2.12 on 2020-05-18 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barber_online_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Ville')),
                ('slug', models.SlugField(editable=False, max_length=40, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='location',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='NPA/Zip'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Country'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100, verbose_name='Coordonées'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.City'),
        ),
    ]
