# Generated by Django 2.2.12 on 2020-05-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_auto_20200518_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=2, max_length=25, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Country'),
        ),
    ]
