# Generated by Django 2.2.12 on 2020-05-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10, verbose_name='Titre')),
                ('subtitle', models.CharField(default='', max_length=50, verbose_name='Sous-Titres')),
                ('picture', models.ImageField(upload_to='', verbose_name='Image')),
                ('btn_caption', models.CharField(default='', max_length=50, verbose_name='Call to Action')),
            ],
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='NPA/Zip Code'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=4, max_length=25, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barbershop.Country'),
        ),
    ]
