# Generated by Django 2.2.12 on 2020-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_auto_20200518_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Titre'),
        ),
    ]
