# Generated by Django 2.2.12 on 2020-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_auto_20200518_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='btn_caption',
            new_name='call_to_action',
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default='', max_length=25, verbose_name='Lien Interne du bouton'),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Position'),
        ),
    ]
