# Generated by Django 2.2.12 on 2020-05-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_auto_20200518_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Image - 2000x1125'),
        ),
    ]
