import { CMS_SERVER_BASE_URL } from '$lib/server/cms';
import type { RequestHandler } from '@sveltejs/kit';

// Proxy the sitemap generated by the Kirby SEO plugin. canonicalBase is set
// to https://for-pro.ch so all <loc> URLs already point to the right domain.
export const GET: RequestHandler = async ({ fetch }) => {
    const response = await fetch(`${CMS_SERVER_BASE_URL}/sitemap.xml`);
    const xml = (await response.text());

    return new Response(xml, {
        headers: { 'Content-Type': 'application/xml' }
    });
};
