server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php-fpm.sock;
    }

    # Kirby .htaccess rules adapted for Nginx
    location ~ /\.ht {
        deny all;
    }

    location ~ /(\.git|\.gitignore|\.svn|\.htaccess|content/.*\.(txt|md|yaml|yml))$ {
        deny all;
    }

    location ~ /kirby/(.*) {
        deny all;
    }

    location ~ /site/(.*) {
        deny all;
    }
}