server {
    listen 80;
    server_name cms.localhost;
    root /var/www/html;
    index index.php index.html;

    default_type text/plain;
    add_header X-Content-Type-Options nosniff;

    rewrite ^/(content|site|kirby)/(.*)$ /error last;
    rewrite ^/\.(?!well-known/) /error last;
    rewrite ^/(?!app\.webmanifest)[^/]+$ /index.php last;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~* \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
