FROM node:24-alpine

RUN npm install -g pnpm

WORKDIR /app
RUN chown node:node /app

USER node

COPY --chown=node:node package.json pnpm-workspace.yaml .npmrc ./
RUN pnpm install

COPY --chown=node:node . .

CMD ["sh", "-c", "pnpm install && pnpm run dev --host 0.0.0.0"]