FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NUXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
