# Generated by Django 2.2.12 on 2024-01-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djradicale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Numero de Telephone')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Email')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Adresse')),
                ('code', models.CharField(default='', max_length=10, verbose_name='NPA/Zip Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
                ('slug', models.SlugField(default='', editable=False, max_length=200, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type de Services')),
                ('duration', models.TimeField(default=None, verbose_name='Durée (minutes)')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provider.Provider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10, verbose_name='Jours')),
                ('day_id', models.IntegerField(default=0, verbose_name='Identifiant du Jour - Lundi 0, Dimanche 6')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closed_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider.Provider')),
            ],
            options={
                'verbose_name': "Heure d'ouverture",
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Zurich')),
                ('online_appointment', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djradicale.DBCollection')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider.Provider')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
    ]
