# Generated by Django 2.2.12 on 2024-01-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='online_appointment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Rendez-vous activé'),
        ),
    ]
